<a href="https://colab.research.google.com/github/nhuyen183/DS-DV-Project/blob/master/Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. Import the numpy package as in the name `np` (easy)

In [1]:
import numpy as np

#### 2. Please print out the numpy version and the configuration (easy)

In [3]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. How can we find the memory size of any array (easy)

In [10]:
a = np.zeros((10,10))
print(a, "%d bytes" % (a.size * a.itemsize))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 800 bytes


#### 4. Let create a null vector of size 10 (easy)

In [4]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 5. Show how to get the documentation of the numpy add function from the command line? (easy)

In [11]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


#### 6. Let create a null vector of size 10 but the fifth value which is 1 (easy)

In [12]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (easy)

In [13]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (i.e., first element becomes last) (easy)

In [15]:
a = np.arange(50)
a = a[::-1]
a

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Could you define a 3x3 matrix with values ranging from 0 to 8 (easy)

In [16]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from `[1,2,0,0,4,0]` (easy)

In [18]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (easy)

In [20]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (easy)

In [21]:
a = np.random.random((3,3,3))
a

array([[[0.15064491, 0.27417752, 0.15367295],
        [0.7729865 , 0.50603111, 0.0724813 ],
        [0.35341449, 0.54594724, 0.26620351]],

       [[0.96907679, 0.92623615, 0.7932429 ],
        [0.58888537, 0.85829851, 0.17405472],
        [0.31485505, 0.52219377, 0.10046384]],

       [[0.21279922, 0.93465241, 0.23765021],
        [0.45176244, 0.31107344, 0.97732473],
        [0.45998153, 0.17870317, 0.51040657]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (easy)

In [22]:
a = np.random.random((10,10))
amin, amax = a.min(), a.max()
print(amin, amax)

0.002110773653859477 0.9923265508925537


#### 14. Create a random vector of size 30 and find the mean value (easy)

In [23]:
a = np.random.random(30)
amean = a.mean()
amean

0.5111075392307824

#### 15. Make a 2d array with 1 on the border and 0 inside (easy)

In [25]:
a = np.ones((10,10))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (easy)

In [31]:
a = np.ones((5,5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (easy)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [34]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (easy)

In [38]:
a = np.diag(1+np.arange(4), k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (easy)

In [40]:
a = np.zeros((8,8), dtype=int)
a[1::2, ::2]=1
a[::2,1::2]=1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index `(x,y,z)` of the 100th element? (easy)

In [41]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (easy)

In [43]:
a = np.tile(np.array([[0,1],[1,0]]),(4,4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (easy)

In [44]:
a = np.random.random((5,5))
a = (a - np.mean(a)) / (np.std(a))
a

array([[ 0.38261608,  0.94537427, -0.96905193, -0.04249227,  0.2566648 ],
       [ 0.00611534, -0.97406014,  1.71186916, -0.95294832,  2.04119035],
       [ 0.83028439, -0.71458137,  0.39711178, -0.79464978, -1.20471662],
       [-0.58656222,  0.09833282, -1.27407028,  0.34238553, -1.41572399],
       [ 0.44385364,  0.69869976, -1.56030227,  0.61271717,  1.72194409]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (easy)

In [45]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (easy)

In [46]:
a = np.dot(np.ones((5,3)), np.ones((3,2)))
a

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (easy)

In [61]:
Z = np.arange(11)
Z[(3<Z) & (Z<=8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (easy)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [55]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (easy)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [62]:
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

ValueError: ignored

#### 28. What are the result of the following expressions? (easy)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [63]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (easy)

In [65]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)),Z))

[-9. -3. -1.  5. -2. -1. -9. -2. -8.  4.]


#### 30. How to find common values between two arrays? (easy)

In [66]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 3 4 6 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (easy)

In [67]:
defaults = np.seterr(all="ignore")
Z = np.ones(1)/0

_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (easy)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [70]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (easy)

In [71]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (intermediate)

In [72]:
Z = np.arange('2016-07', '2016-08',dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute `((A+B)*(-A/2))` in place (without copy)? (intermediate)

In [75]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B, out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (intermediate)

In [78]:
Z = np.random.uniform(0,10,10)

print(Z-Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[6. 1. 7. 5. 4. 2. 0. 6. 1. 1.]
[6. 1. 7. 5. 4. 2. 0. 6. 1. 1.]
[6. 1. 7. 5. 4. 2. 0. 6. 1. 1.]
[6 1 7 5 4 2 0 6 1 1]
[6. 1. 7. 5. 4. 2. 0. 6. 1. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (intermediate)

In [79]:
Z = np.zeros((5,5))
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (easy)

In [81]:
def generate():
  for x in range(10):
    yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (intermediate)

In [82]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (intermediate)

In [83]:
Z = np.random.random(10)
Z.sort()
Z

array([0.11593609, 0.14485551, 0.15760109, 0.30696948, 0.33295294,
       0.46255518, 0.51812364, 0.6376928 , 0.71025037, 0.99166726])

#### 41. How to sum a small array faster than np.sum? (intermediate)

In [84]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (intermediate)

In [85]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal=np.allclose(A,B)
equal

False

#### 43. Make an array immutable (read-only) (intermediate)

In [86]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0]=1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (intermediate)

In [88]:
Z = np.random.random((10,2))
X,Y = Z[:,0],Z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[0.61248757 0.60209116 0.69560331 1.30224074 0.20365588 0.69738343
 0.97399938 0.606435   0.74289588 0.21535412]
[0.40538766 1.09227152 0.8140958  0.81070314 0.20637692 0.24786471
 0.71110858 0.69384398 0.68019059 0.63716132]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (intermediate)

In [89]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.65876164 0.23619683 0.18277789 0.16388565 0.00315709 0.88209157
 0.50899848 0.21385757 0.31349911 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (intermediate)

In [90]:
Z = np.zeros((5,5), [('x', float), ('y', float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix `C` `(Cij =1/(xi - yj))` (intermediate)

In [92]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (intermediate)

In [94]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (intermediate)

In [95]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
Z

ValueError: ignored

#### 50. How to find the closest value (to a given scalar) in a vector? (intermediate)

In [110]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

28


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (intermediate)

In [109]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (intermediate)

In [104]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.27210831 0.78817864 0.06639225 0.59653748 0.55532902
  0.56519532 1.02688746 0.9982052  0.90968987]
 [0.27210831 0.         0.6595773  0.21886338 0.46356173 0.33934542
  0.40014983 0.95253676 0.82453661 0.72302664]
 [0.78817864 0.6595773  0.         0.7263091  0.19789665 0.36758693
  0.26304638 0.32446501 0.24879808 0.22170131]
 [0.06639225 0.21886338 0.7263091  0.         0.53312193 0.48916398
  0.49960492 0.97283526 0.93330295 0.84396072]
 [0.59653748 0.46356173 0.19789665 0.53312193 0.         0.21088663
  0.0856844  0.4961892  0.40620801 0.33141835]
 [0.55532902 0.33934542 0.36758693 0.48916398 0.21088663 0.
  0.12553723 0.68902438 0.4900773  0.38547425]
 [0.56519532 0.40014983 0.26304638 0.49960492 0.0856844  0.12553723
  0.         0.57525652 0.43526662 0.3445689 ]
 [1.02688746 0.95253676 0.32446501 0.97283526 0.4961892  0.68902438
  0.57525652 0.         0.39874879 0.4599359 ]
 [0.9982052  0.82453661 0.24879808 0.93330295 0.40620801 0.4900773
  0.43526662 0.398748

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? (intermediate)

In [106]:
Z = np.arange(10, dtype=np.float32).astype(np.int32, copy=False)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (intermediate)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [108]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                ,  , 9,10,11\n""")
Z = np.genfromtxt(s,delimiter=",",dtype=np.int)
Z

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (intermediate)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.

#### 56. Generate a generic 2D Gaussian-like array (intermediate)

#### 57. How to randomly place p elements in a 2D array? (intermediate)

#### 58. Subtract the mean of each row of a matrix (intermediate)

#### 59. How to sort an array by the nth column? (intermediate)

#### 60. How to tell if a given 2D array has null columns? (intermediate)

#### 61. Find the nearest value from a given value in an array (intermediate)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (intermediate)

#### 63. Create an array class that has a name attribute (intermediate)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (advanced)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (advanced)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (intermediate)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (advanced)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (advanced)

#### 69. How to get the diagonal of a dot product? (advanced)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (advanced)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (advanced)

#### 72. How to swap two rows of an array? (advanced)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (advanced)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (advanced)

#### 75. How to compute averages using a sliding window over an array? (advanced)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (advanced)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (advanced)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (advanced)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (advanced)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (advanced)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (advanced)

#### 82. Compute a matrix rank (advanced)

#### 83. How to find the most frequent value in an array? (advanced)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (advanced)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (advanced)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (advanced)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (advanced)

#### 88. How to implement the Game of Life using numpy arrays? (advanced)

#### 89. How to get the n largest values of an array (advanced)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (advanced)

#### 91. How to create a record array from a regular array? (advanced)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (advanced)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (advanced)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (advanced)

#### 95. Convert a vector of ints into a matrix binary representation (advanced)

#### 96. Given a two dimensional array, how to extract unique rows? (advanced)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (advanced)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (advanced)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (advanced)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (advanced)